### ISSUE TITLE
Segfault when constructing a class with a vector of strings

### ISSUE THREAD

**Issue by hhenson** [pybind/pybind11#1729]
## Issue description

When constructing an object with a parameter of std::vector<std::string>> the py::init fails with a segfault that is caused when the list_caster attempts to clear the value property.

```
template <typename Type, typename Value> struct list_caster {
    using value_conv = make_caster<Value>;

    bool load(handle src, bool convert) {
        if (!isinstance<sequence>(src) || isinstance<str>(src))
            return false;
        auto s = reinterpret_borrow<sequence>(src);
        value.clear();  <--- This is what is ultimately causing the failure
```

## Reproducible example code

```
class TestVectorOfString {
    public:
        using s_ptr = std::shared_ptr<TestVectorOfString>;
        using v_of_s = std::vector<std::string>;

        TestVectorOfString(v_of_s v) : v{std::move(v_)}{}

        const v_of_s v;
};

PYBIND11_MODULE(_tst, m) {
    py::class_<TestVectorOfString, TestVectorOfString::s_ptr>(m, "TestVectorOfString")
                .def(py::init<TestVectorOfString::v_of_s>(), "v"_a)
                .def_readonly("v", &TestVectorOfString::v);
}
```

Then in python all that is required to to do:
````
import _tst
_tst.TestVectorOfString([])
````

This produces a segfault.

I have reproduced this using VS2017 and GCC 7.3.1.
I am using Anaconda python 3.6
I can also re-produce this when using an unordered_set.
I don't have the same problem when using a vector of int.

**Comment by eacousineau** [comment]
This does not fail with the following:
pybind11 @ 25abf7e
Ubuntu 18.04
GCC 7.3.0

Repro code: https://github.com/eacousineau/repro/commit/1fc91a806f662ac6f2708c796292f00193ee1c14

I *think* this was fixed by the resolution of #1561 via #1603 (adc2cdd5).
Can you try using the latest `master` (which incorporates this and other bugfixes)?

**Comment by hhenson** [comment]
I have tried the master branch. Whilst I can't replicate standalone, The exact same code in my project still fails. I have created the standalone test to be configured exactly the same as the main project and still see the problem. I am trying to cut out chunks of the master project to see if I can find out what is causing the problem. Hopefully I can narrow down the problem a bit further.

**Comment by hhenson** [comment]
Managed to resolve the problem by extracting imports into a single header (pybind11 and stl) and then ensuring that each file that imported pybind headers use the new header. This seems to have resolved the issue. I guess there were some import ordering issues that was causing the problem.

**Comment by eacousineau** [comment]
Thanks for posting the solution!

Import ordering still *very* odd... Was this with `pybind11` headers only?
Were you still getting a segfault, or did it turn into an error saying that you should import `pybind11/stl.h`?

If it does create a segfault with `pybind11`, I'd like to know, because it's something I'd hate to run into too!

**Comment by hhenson** [comment]
Segfaulted. 

In most places I had pybind11.h followed by stl.h but in a few places I only imported pybind11.h as it did not appear that stl.h was needed (I.e. where I was just using pyobject) but it appears the consequence was that the sequence converter got affected in that the binding code knew to call the sequence converter, but the constructor of the sequence caster was never called. This left value uninitialised and thus caused a segfault. 
Obviously when I say the constructor was never called it could also just be that the binding code assumed to find a valid caster and cast a pointer incorrectly, I never determined exactly why that was happening. 

Hope that helps. 

Howard
